python create_annotation_sqlite.py homo_sapiens_gencode25 /home/jack/projects/index-construction/organism_sqlites/homo_sapiens_gencode25/gencode.v25.annotation.gff3 /home/jack/projects/index-construction/organism_sqlites/homo_sapiens_gencode25/gencode.v25.transcripts.fa 0 ENST00000450305.2 DDX11L1 /home/jack/projects/index-construction/organism_sqlites/homo_sapiens_gencode25/homo_sapiens.gencode25.sqlite

python create_annotation_sqlite.py homo_sapiens_genocde28 /home/jack/projects/index-construction/organism_sqlites/homo_sapiens_gencode28/gencode.v28.annotation.gff3 /home/jack/projects/index-construction/organism_sqlites/homo_sapiens_gencode28/gencode.v28.transcripts.fa 0 ENST00000456328.2 DDX11L1 /home/jack/projects/index-construction/organism_sqlites/homo_sapiens_gencode28/homo_sapiens.gencode28.sqlite 

python create_annotation_sqlite.py mus_musculus_gencode10 /home/jack/projects/index-construction/organism_sqlites/mus_musculus_m10/gencode.vM10.annotation.gff3 /home/jack/projects/index-construction/organism_sqlites/mus_musculus_m10/gencode.vM10.transcripts.fa 0 ENSMUST00000193812.1 4933401J01Rik /home/jack/projects/index-construction/organism_sqlites/mus_musculus_m10/mus_musculus.gencode10.sqlite

python create_annotation_sqlite.py mus_musculus_gencode28 /home/jack/projects/index-construction/organism_sqlites/mus_musculus_m28/gencode.vM28.annotation.gff3 /home/jack/projects/index-construction/organism_sqlites/mus_musculus_m28/gencode.vM28.transcripts.fa 0 ENSMUST00000193812.2 4933401J01Rik /home/jack/projects/index-construction/organism_sqlites/mus_musculus_m28/mus_musculus.gencode28.sqlite

python create_annotation_sqlite.py arabidopsis_TAIR10 /home/jack/projects/index-construction/organism_sqlites/Arabidopsis/Arabidopsis_thaliana.TAIR10.55.gff3 /home/jack/projects/index-construction/organism_sqlites/Arabidopsis/Arabidopsis_thaliana.TAIR10.cdna.all.fa 0 AT1G01010.1 NAC001 /home/jack/projects/index-construction/organism_sqlites/Arabidopsis/arabidopsis_thaliana.TAIR10.sqlite

python create_annotation_sqlite.py drosophila_melanogastor_r6 /home/jack/projects/index-construction/organism_sqlites/drosophila_melanogaster_dm6/dmel-all-r6.48.gff /home/jack/projects/index-construction/organism_sqlites/drosophila_melanogaster_dm6/dmel-all-transcript-r6.48.fasta 0 FBgn0266909 CR45369 /home/jack/projects/index-construction/organism_sqlites/drosophila_melanogaster_dm6/drosophila_melanogastor.flybaser6_46.sqltie

python create_annotation_sqlite.py E_coli_K12_MG1655 /home/jack/projects/index-construction/organism_sqlites/E_coli_K12_MG1655/Escherichia_coli_str_k_12_substr_mg1655_gca_000005845.ASM584v2.49.gff3 /home/jack/projects/index-construction/organism_sqlites/E_coli_K12_MG1655/Escherichia_coli_str_k_12_substr_mg1655_gca_000005845.ASM584v2.cdna.all.fa 0 AAC73114 thrB /home/jack/projects/index-construction/organism_sqlites/E_coli_K12_MG1655/Escherichia_coli_str_k_12_substr_mg1655.sqlite

python create_annotation_sqlite.py sacCer_r64 /home/jack/projects/index-construction/organism_sqlites/sacCer_R64/Saccharomyces_cerevisiae.R64-1-1.55.gff3 /home/jack/projects/index-construction/organism_sqlites/sacCer_R64/Saccharomyces_cerevisiae.R64-1-1.cdna.all.fa 0 YAL069W_mRNA YAL069W /home/jack/projects/index-construction/organism_sqlites/sacCer_R64/Saccharomyces_cerevisiae.R64.sqlite
